package compat

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

// Evidence is where a row of the table got its Controller from. There are two
// kinds and there is no third, so it is a type rather than a loose string: the
// generator decides which one a row is by reading its tests, and a value
// outside these two would be a row nobody could say what backed.
type Evidence string

const (
	// FromContainer is a row CI exercised against a dockerized Controller, and
	// the only kind that can carry a matrix of versions.
	FromContainer Evidence = "container"
	// FromRecording is a row exercised against recorded responses from real
	// hardware, which is one Controller version and always will be
	// (ADR-0008, ADR-0013).
	FromRecording Evidence = "recording"
)

// Matrix is what the suite actually proved, as generated by tools/compat and
// shipped inside the binary. Everything in it came from a run: the versions are
// the ones whose jobs passed, and an area is here because its tests ran, not
// because a file said they should.
type Matrix struct {
	// Image is the container image the matrix versions are tags of.
	Image string `json:"image"`
	// Floor is the oldest version the promise reaches.
	Floor string `json:"floor"`
	// Versions are the dockerized Controller versions CI passed against,
	// newest first.
	Versions []string `json:"versions"`
	// Recording is the hardware the replayed areas were tested against.
	Recording Recording `json:"recording"`
	// Areas are the rows of the table.
	Areas []Coverage `json:"areas"`
}

// Recording is the recorded Controller the replayed areas are evidence about.
// It is one version because a recording is one router (ADR-0011).
type Recording struct {
	Version string `json:"version"`
	Source  string `json:"source"`
}

// Coverage is one row: an area, the tests behind it, and the Controller
// versions those tests passed against.
//
// It deliberately does not count the tests. A count would be a true and mildly
// interesting number that changed every time anybody added a test, and this
// file is regenerated by running the whole matrix — so it would put half an
// hour of Docker in the way of a one-line test. What is here changes when the
// promise changes, which is the only time regenerating it is the point.
type Coverage struct {
	Name string `json:"name"`
	// Tests is the file the row's evidence came out of. Nothing reads it —
	// it is provenance for whoever opens the generated file and wants to know
	// which tests a row is a claim about.
	Tests    string   `json:"tests"`
	Evidence Evidence `json:"evidence"`
	Versions []string `json:"versions"`
	// Why this area is not tested against a container, on the areas that are
	// not. Empty everywhere else.
	Why string `json:"why,omitempty"`
}

// CompareVersions orders two Controller versions oldest-first, and puts one it
// cannot read last so a sort never depends on which side of the comparison it
// landed on.
func CompareVersions(a, b string) int {
	left, leftOK := parseRelease(a)
	right, rightOK := parseRelease(b)
	switch {
	case leftOK && rightOK:
		return left.compare(right)
	case leftOK:
		return 1
	case rightOK:
		return -1
	default:
		return strings.Compare(a, b)
	}
}

//go:embed matrix.json
var evidence []byte

// shipped is decoded once, at startup, and left empty if that fails.
//
// Empty is the safe failure here rather than a panic: this evidence decides
// whether unifig prints a warning, and a tool that will not start because it
// cannot describe its own test coverage would be a worse answer to a broken
// generated file than a tool that says nothing about it. A unit test asserts
// the committed file is not that.
var shipped = decodeShipped()

func decodeShipped() Matrix {
	var m Matrix
	if err := json.Unmarshal(evidence, &m); err != nil {
		return Matrix{}
	}
	return m
}

// Shipped is the compatibility evidence built into this binary.
func Shipped() Matrix { return shipped }

// Warning is what an operator should be told about the Controller in front of
// them, or "" when the matrix covers it.
//
// It is a warning and never a refusal. unifig has no way to know that an
// untested Controller is a broken one — the versions in the matrix are the ones
// somebody ran the suite against, not the ones Ubiquiti built the API for — so
// the operator gets the fact and keeps their tool.
//
// It asks the container matrix and nothing else. The recording's own version is
// deliberately not in that set even though the replayed rows are attributed to
// it: a recording is evidence about four areas, and staying quiet for a version
// where the other five were never run would be the warning claiming more than
// anybody tested. The two versions coincide today, which is exactly why the
// distinction has to be made here rather than left to be noticed when
// `make record-udr` is next run against newer firmware.
func (m Matrix) Warning(version string) string {
	if len(m.Versions) == 0 {
		// A binary carrying no evidence promises nothing, so it has nothing to
		// warn about.
		return ""
	}

	const table = "docs/COMPATIBILITY.md"
	if version == "" {
		return fmt.Sprintf("this Controller did not say which UniFi Network version it runs, so unifig cannot"+
			" tell whether it is one of the versions it has been tested against (%s). Carrying on anyway.", table)
	}

	running, ok := parseRelease(version)
	if !ok {
		return fmt.Sprintf("this Controller says it runs UniFi Network %q, which unifig cannot read as a version,"+
			" so it cannot tell whether it is one it has been tested against (%s). Carrying on anyway.", version, table)
	}

	newest, oldest := m.Versions[0], m.Versions[len(m.Versions)-1]
	for _, candidate := range m.Versions {
		if parsed, ok := parseRelease(candidate); ok && parsed.compare(running) == 0 {
			return ""
		}
	}

	if parsed, ok := parseRelease(newest); ok && running.compare(parsed) > 0 {
		return fmt.Sprintf("this Controller runs UniFi Network %s, which is newer than any version unifig has been"+
			" tested against — the newest is %s (%s). Carrying on anyway.", version, newest, table)
	}
	if parsed, ok := parseRelease(oldest); ok && running.compare(parsed) < 0 {
		return fmt.Sprintf("this Controller runs UniFi Network %s, which is older than any version unifig has been"+
			" tested against — the oldest is %s (%s). Carrying on anyway.", version, oldest, table)
	}
	return fmt.Sprintf("this Controller runs UniFi Network %s, which unifig has not been tested against; the tested"+
		" versions are %s (%s). Carrying on anyway.", version, listOf(m.Versions), table)
}

// Warning asks the evidence this binary ships with.
func Warning(version string) string { return shipped.Warning(version) }

// NextMinor is the version one minor release past the newest one tested — a
// version this matrix does not carry, whatever it holds. It exists so the
// published table can show a real example of the warning rather than quote a
// version somebody wrote down, which a later matrix could quietly make tested.
func (m Matrix) NextMinor() string {
	if len(m.Versions) == 0 {
		return ""
	}
	newest, ok := parseRelease(m.Versions[0])
	if !ok || len(newest) < 2 {
		return ""
	}
	return fmt.Sprintf("%d.%d.0", newest[0], newest[1]+1)
}

// listOf reads a list out the way a person would say it.
func listOf(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	default:
		return strings.Join(items[:len(items)-1], ", ") + " and " + items[len(items)-1]
	}
}
