// Package cli_test drives unifig's whole command layer the way the operator
// does — a verb, arguments, an environment, and whatever lands on stdout,
// stderr and the exit code.
//
// The e2e suite is the house pattern for this, and it runs the real binary
// against a real dockerized Controller. Validate cannot live there: it is
// offline by design, and requiring Docker to prove that would be an odd way to
// demonstrate that no Controller is needed. So these tests take the highest
// seam that is still Docker-free — cli.Run, the top-level engine behind main —
// and assert only on what a shell would see. Being an external test package,
// they cannot reach past that seam even by accident.
package cli_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/liambeeton/unifig/internal/cli"
)

// unreachableController is a Controller that is guaranteed not to answer:
// port 1 on the loopback interface. Validate runs with this in the
// environment throughout, so any test passing here is a test that proves
// validate never opened a connection.
const unreachableController = "https://127.0.0.1:1"

type result struct {
	exitCode int
	stdout   string
	stderr   string
}

// runValidate writes body to a config file and validates it, with connection
// config that would fail loudly if validate ever tried to use it.
func runValidate(t *testing.T, body string, env map[string]string) result {
	t.Helper()
	path := filepath.Join(t.TempDir(), "unifig.yaml")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	for name, value := range env {
		t.Setenv(name, value)
	}
	return run(t, "validate", path)
}

func run(t *testing.T, args ...string) result {
	t.Helper()
	t.Setenv("UNIFIG_HOST", unreachableController)
	t.Setenv("UNIFIG_API_KEY", "unused-by-validate")

	var stdout, stderr strings.Builder
	code := cli.Run(context.Background(), args, noInput, &stdout, &stderr)
	return result{exitCode: code, stdout: stdout.String(), stderr: stderr.String()}
}

// noInput is a closed stdin. Nothing these tests run should ever ask the
// operator a question, so anything that does gets EOF and has to cope.
var noInput = strings.NewReader("")

// mustPass fails the test unless validate accepted the file, printing what it
// objected to.
func (r result) mustPass(t *testing.T) result {
	t.Helper()
	if r.exitCode != 0 {
		t.Fatalf("validate exited %d, want 0\nstderr: %s", r.exitCode, r.stderr)
	}
	return r
}

// mustFailWith fails the test unless validate rejected the file with a message
// mentioning every fragment — the things an operator needs in order to act.
func (r result) mustFailWith(t *testing.T, fragments ...string) result {
	t.Helper()
	if r.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1\nstdout: %s\nstderr: %s", r.exitCode, r.stdout, r.stderr)
	}
	if r.stdout != "" {
		t.Errorf("validate should print nothing on stdout when it fails, got: %s", r.stdout)
	}
	for _, fragment := range fragments {
		if !strings.Contains(r.stderr, fragment) {
			t.Errorf("stderr should mention %q, got:\n%s", fragment, r.stderr)
		}
	}
	return r
}

// exportedYAML is the shape `unifig export` writes, as an independent literal
// rather than something generated by the code under test.
const exportedYAML = `networks:
  - name: Default
    subnet: 192.168.1.1/24
  - name: IoT
    vlan: 20
    subnet: 10.20.0.1/24
`

func TestValidateAcceptsWhatExportProduces(t *testing.T) {
	runValidate(t, exportedYAML, nil).mustPass(t)
}

func TestValidateReportsSuccessOnStdout(t *testing.T) {
	res := runValidate(t, exportedYAML, nil).mustPass(t)

	if !strings.Contains(res.stdout, "is valid") {
		t.Errorf("stdout should confirm the file is valid, got: %q", res.stdout)
	}
	if res.stderr != "" {
		t.Errorf("stderr should stay empty on success, got: %q", res.stderr)
	}
}

func TestValidateNeedsNoControllerAndNoConnectionConfig(t *testing.T) {
	// Not merely unreachable — absent. Export fails without these; validate
	// must not care that they are missing.
	t.Setenv("UNIFIG_HOST", "")
	t.Setenv("UNIFIG_API_KEY", "")
	if err := os.Unsetenv("UNIFIG_HOST"); err != nil {
		t.Fatal(err)
	}
	if err := os.Unsetenv("UNIFIG_API_KEY"); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(t.TempDir(), "unifig.yaml")
	if err := os.WriteFile(path, []byte(exportedYAML), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}

	var stdout, stderr strings.Builder
	if code := cli.Run(context.Background(), []string{"validate", path}, noInput, &stdout, &stderr); code != 0 {
		t.Fatalf("validate exited %d with no connection config, want 0\nstderr: %s", code, stderr.String())
	}
}

func TestValidateDefaultsToUnifigYAMLInTheWorkingDirectory(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "unifig.yaml"), []byte(exportedYAML), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	t.Chdir(dir)

	res := run(t, "validate").mustPass(t)
	if !strings.Contains(res.stdout, "unifig.yaml") {
		t.Errorf("stdout should name the file it validated, got: %q", res.stdout)
	}
}

func TestValidateReportsAMissingFile(t *testing.T) {
	res := run(t, "validate", filepath.Join(t.TempDir(), "nowhere.yaml"))

	if res.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "nowhere.yaml") {
		t.Errorf("stderr should name the file it could not read, got: %s", res.stderr)
	}
	// The likeliest reason there is no config file is that the operator has
	// not made one yet, and export is how they do that.
	if !strings.Contains(res.stderr, "unifig export") {
		t.Errorf("stderr should point at export as the way to create one, got: %s", res.stderr)
	}
}

func TestValidateRejectsAMultiDocumentFileRatherThanIgnoringTheRest(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
---
wlans:
  - name: Home IoT
    network: IoT
`, nil).mustFailWith(t, "one YAML document")
}

func TestValidateRejectsAMisspelledField(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnett: 10.20.0.1/24
`, nil).mustFailWith(t, "line 3", "networks[0].subnett", "subnett")
}

func TestValidateRejectsAnUnknownSection(t *testing.T) {
	runValidate(t, `netwroks:
  - name: IoT
`, nil).mustFailWith(t, "netwroks")
}

func TestValidateRejectsAMissingName(t *testing.T) {
	runValidate(t, `networks:
  - vlan: 20
`, nil).mustFailWith(t, "networks[0]", "name")
}

func TestValidateRejectsAMalformedSubnet(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnet: 10.20.0.1
`, nil).mustFailWith(t, "line 3", "networks[0].subnet", "10.20.0.1/24")
}

func TestValidateRejectsAnOutOfRangeVLAN(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 5000
`, nil).mustFailWith(t, "networks[0].vlan", "4094")
}

func TestValidateReportsEveryProblemAtOnce(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    subnet: nonsense
  - vlan: 5000
`, nil).mustFailWith(t, "networks[0].subnet", "networks[1]", "networks[1].vlan")

	// File order, so the list reads like the file the operator is looking at.
	subnet := strings.Index(res.stderr, "networks[0].subnet")
	vlan := strings.Index(res.stderr, "networks[1].vlan")
	if subnet > vlan {
		t.Errorf("problems should be listed in file order, got:\n%s", res.stderr)
	}
}

func TestValidateRejectsAnEmptyFile(t *testing.T) {
	runValidate(t, "# nothing here yet\n", nil).mustFailWith(t, "empty")
}

func TestValidateRejectsBrokenYAML(t *testing.T) {
	runValidate(t, "networks: [\n", nil).mustFailWith(t, "YAML")
}

func TestValidateCatchesAWLANPointingAtAnUndefinedNetwork(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
wlans:
  - name: Home IoT
    network: Gest
`, nil).mustFailWith(t, "line 6", `wlans[0].network`, `"Gest"`, `"IoT"`)
}

func TestValidateAcceptsAWLANPointingAtADefinedNetwork(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
`, nil).mustPass(t)
}

// The whole point of `${ENV_VAR}`: a committed config file that carries a
// passphrase without carrying the passphrase.
func TestValidateAcceptsAPassphraseSuppliedByTheEnvironment(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    passphrase: ${GUEST_PASSPHRASE}
`, map[string]string{"GUEST_PASSPHRASE": "correct horse battery"}).mustPass(t)
}

// A passphrase the config leaves out is a passphrase unifig does not manage,
// the same rule as every other omitted field (ADR-0004).
func TestValidateAcceptsAWLANWithNoPassphrase(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
`, nil).mustPass(t)
}

// The bounds are the Controller's own: it refuses a WPA-PSK passphrase outside
// 8 to 64 characters, so unifig refuses one offline rather than letting an
// apply get halfway and stop.
func TestValidateRejectsAPassphraseTheControllerWouldRefuse(t *testing.T) {
	for _, supplied := range []struct{ what, value, want string }{
		{"too short", "short", "8 characters"},
		{"too long", strings.Repeat("a", 65), "64 characters"},
		// Caught here rather than by the Controller partway through an apply.
		{"not printable ASCII", "pässwörd123", "printable ASCII"},
	} {
		t.Run(supplied.what, func(t *testing.T) {
			runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    passphrase: ${GUEST_PASSPHRASE}
`, map[string]string{"GUEST_PASSPHRASE": supplied.value}).
				mustFailWith(t, "line 7", "wlans[0].passphrase", supplied.want)
		})
	}
}

// A validation message is printed, logged and pasted into bug reports, so the
// one thing it must never contain is the secret it is complaining about.
func TestValidateNeverEchoesAPassphrase(t *testing.T) {
	const secret = "sh0rt"
	for _, supplied := range []struct{ what, body, value string }{
		{"too short", "passphrase: ${GUEST_PASSPHRASE}\n", secret},
		{"too long", "passphrase: ${GUEST_PASSPHRASE}\n", strings.Repeat(secret, 20)},
		// The one that pays for the secretFields list: a pattern failure quotes
		// what it rejected everywhere else in unifig.
		{"not printable ASCII", "passphrase: ${GUEST_PASSPHRASE}\n", "pässwörd" + secret},
		{"the wrong type", "passphrase:\n      - ${GUEST_PASSPHRASE}\n", secret},
	} {
		t.Run(supplied.what, func(t *testing.T) {
			res := runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    `+supplied.body, map[string]string{"GUEST_PASSPHRASE": supplied.value})

			if res.exitCode != 1 {
				t.Fatalf("validate exited %d, want 1\nstderr: %s", res.exitCode, res.stderr)
			}
			if strings.Contains(res.stderr, secret) {
				t.Errorf("validate printed the passphrase it was complaining about:\n%s", res.stderr)
			}
		})
	}
}

func TestValidateCatchesDuplicateNetworkNames(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    vlan: 20
  - name: IoT
    vlan: 21
`, nil).mustFailWith(t, "line 4", "networks[1].name", `"IoT"`)

	if strings.Count(res.stderr, "already defined") != 1 {
		t.Errorf("a duplicated name should be reported once, got:\n%s", res.stderr)
	}
}

// A zone groups networks, and the networks it groups are checked against the
// file exactly as a WLAN's network is.
func TestValidateAcceptsAZoneGroupingNetworksTheFileDefines(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
  - name: Guest
    vlan: 30
zones:
  - name: Untrusted
    networks:
      - IoT
      - Guest
`, nil).mustPass(t)
}

func TestValidateCatchesAZoneHoldingAnUndefinedNetwork(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
zones:
  - name: Untrusted
    networks:
      - IoT
      - Guset
`, nil).mustFailWith(t, "line 8", "zones[0].networks[1]", `"Guset"`, `"IoT"`)
}

// ADR-0004 as usual: a zone that states no membership manages none, which is how
// an operator names a built-in zone in order to write policies about it without
// taking over what is in it.
func TestValidateAcceptsAZoneThatManagesNoMembership(t *testing.T) {
	runValidate(t, `zones:
  - name: External
`, nil).mustPass(t)
}

// The other half of that rule: an empty list is a statement, and it says the
// zone should hold nothing.
func TestValidateAcceptsAZoneStatedAsHoldingNothing(t *testing.T) {
	runValidate(t, `zones:
  - name: Quarantine
    networks: []
`, nil).mustPass(t)
}

func TestValidateCatchesDuplicateZoneNames(t *testing.T) {
	runValidate(t, `zones:
  - name: Untrusted
  - name: Untrusted
`, nil).mustFailWith(t, "line 3", "zones[1].name", `"Untrusted"`)
}

// A policy is its verdict and both of its ends, and the schema requires all
// three: a policy that allowed or blocked nothing in particular is not one.
func TestValidateAcceptsAFirewallPolicyBetweenTwoZones(t *testing.T) {
	runValidate(t, `zones:
  - name: Untrusted
firewall-policies:
  - name: Untrusted to internet
    action: allow
    source: Untrusted
    destination: External
`, nil).mustPass(t)
}

func TestValidateRejectsAFirewallPolicyMissingAnEnd(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Half a rule
    action: allow
    source: Untrusted
`, nil).mustFailWith(t, "firewall-policies[0]", "destination")
}

func TestValidateRejectsAVerdictUnifigDoesNotModel(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Maybe
    action: ponder
    source: Untrusted
    destination: External
`, nil).mustFailWith(t, "line 3", "firewall-policies[0].action", `"ponder"`, `"block"`)
}

// The zone a policy names is deliberately not checked against the file. The
// policies worth writing are mostly about the Controller's own built-in zones —
// External is the internet — and those are matchable but never in the config, so
// checking here would reject the commonest policy there is. It is resolved when
// unifig reads the Controller instead (ADR-0010's rule for WAN slots).
func TestValidateAcceptsAPolicyNamingAZoneOnlyTheControllerHas(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Guests out
    action: allow
    source: Internal
    destination: External
`, nil).mustPass(t)
}

func TestValidateCatchesDuplicateFirewallPolicyNames(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Twice
    action: allow
    source: Internal
    destination: External
  - name: Twice
    action: block
    source: Internal
    destination: External
`, nil).mustFailWith(t, "line 6", "firewall-policies[1].name", `"Twice"`)
}

// The other half of that rule, and the one a real site depends on: a policy's
// key is its name *and* both ends, so the same name on a different pair of zones
// is two policies rather than one written twice. A file describing a migrated
// Controller has to be able to say this — its predefined set repeats "Allow All
// Traffic" once per pair (ADR-0001, issue #24).
func TestValidateAcceptsPoliciesSharingANameOnDifferentZonePairs(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Allow All Traffic
    action: allow
    source: Internal
    destination: External
  - name: Allow All Traffic
    action: allow
    source: Internal
    destination: Gateway
  - name: Allow All Traffic
    action: allow
    source: Gateway
    destination: External
`, nil).mustPass(t)
}

// Direction is part of the key, not decoration: a policy from Internal to
// External and one from External to Internal govern opposite traffic and are
// two policies, however alike they look.
func TestValidateAcceptsAPolicyAndItsReverse(t *testing.T) {
	runValidate(t, `firewall-policies:
  - name: Between Them
    action: allow
    source: Internal
    destination: External
  - name: Between Them
    action: block
    source: External
    destination: Internal
`, nil).mustPass(t)
}

// A port forward is the record of one exposed service, so everything that makes
// up the exposure is required: which port answers, which host it reaches, and
// which traffic it passes.
func TestValidateAcceptsAPortForward(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Home Assistant
    port: 443
    forward-ip: 10.20.0.10
    forward-port: 8123
    protocol: tcp
`, nil).mustPass(t)
}

// The one optional field, and the reason it is optional: an omitted `source` is
// unmanaged like every other omission (ADR-0004), so an operator who narrowed a
// forward in the Controller's UI does not have to restate it here to keep it.
func TestValidateAcceptsAPortForwardRestrictedToOneSource(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Admin
    port: 22
    forward-ip: 10.20.0.10
    forward-port: 22
    protocol: tcp
    source: 203.0.113.0/24
`, nil).mustPass(t)
}

func TestValidateRejectsAPortForwardThatNamesNoHost(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Half a forward
    port: 443
    forward-port: 8123
    protocol: tcp
`, nil).mustFailWith(t, "port-forwards[0]", "forward-ip")
}

func TestValidateRejectsAPortOutsideTheRangeAPortCanTake(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Too high
    port: 70000
    forward-ip: 10.20.0.10
    forward-port: 8123
    protocol: tcp
`, nil).mustFailWith(t, "line 3", "port-forwards[0].port", "65535")
}

// unifig models a single port at each end. A range or a list is what the
// Controller can hold and this file cannot state, and saying so offline is
// better than an apply that sends the Controller a port it will refuse.
func TestValidateRejectsAPortGivenAsARange(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Game server
    port: 27015-27020
    forward-ip: 10.20.0.10
    forward-port: 27015
    protocol: udp
`, nil).mustFailWith(t, "line 3", "port-forwards[0].port", "integer")
}

func TestValidateRejectsAProtocolUnifigDoesNotModel(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Odd one
    port: 443
    forward-ip: 10.20.0.10
    forward-port: 8123
    protocol: sctp
`, nil).mustFailWith(t, "line 6", "port-forwards[0].protocol", `"sctp"`, `"tcp_udp"`)
}

func TestValidateRejectsASourceThatIsNotAnAddress(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Admin
    port: 22
    forward-ip: 10.20.0.10
    forward-port: 22
    protocol: tcp
    source: the office
`, nil).mustFailWith(t, "line 7", "port-forwards[0].source", `"the office"`, "203.0.113.0/24")
}

func TestValidateCatchesDuplicatePortForwardNames(t *testing.T) {
	runValidate(t, `port-forwards:
  - name: Twice
    port: 443
    forward-ip: 10.20.0.10
    forward-port: 8123
    protocol: tcp
  - name: Twice
    port: 8443
    forward-ip: 10.20.0.11
    forward-port: 8443
    protocol: tcp
`, nil).mustFailWith(t, "line 7", "port-forwards[1].name", `"Twice"`)
}

// The forward's target is an address rather than a reference, so there is
// nothing in the file for it to match — a forward to a host on a network this
// file has never heard of is perfectly valid config.
func TestValidateAcceptsAPortForwardToAnAddressTheFileSaysNothingAbout(t *testing.T) {
	runValidate(t, `networks:
  - name: Default
    subnet: 192.168.1.1/24
port-forwards:
  - name: Elsewhere
    port: 443
    forward-ip: 10.99.0.10
    forward-port: 443
    protocol: tcp
`, nil).mustPass(t)
}

// A DHCP Reservation is keyed by MAC address rather than by a name, because it
// is not a standalone object at all: it is the fixed-IP half of the Controller's
// per-client record, and the MAC is what identifies the client.
func TestValidateAcceptsADHCPReservation(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "00:11:22:33:44:55"
    ip: 10.20.0.50
`, nil).mustPass(t)
}

// The reservation is the fixed address, so both halves of it are required: the
// client it is for, and the address it pins them to.
func TestValidateRejectsAReservationWithNoAddress(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "00:11:22:33:44:55"
`, nil).mustFailWith(t, "dhcp-reservations[0]", "ip")
}

func TestValidateRejectsAReservationWithNoMAC(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - ip: 10.20.0.50
`, nil).mustFailWith(t, "dhcp-reservations[0]", "mac")
}

// The Controller's own form for a MAC, which is what it stores and what it
// refuses anything else as: six hex pairs with colons between them.
func TestValidateRejectsAMACTheControllerWouldRefuse(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "001122334455"
    ip: 10.20.0.50
`, nil).mustFailWith(t, "dhcp-reservations[0].mac", "001122334455", "00:1a:2b")
}

func TestValidateRejectsAReservedAddressThatIsNotAnAddress(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "00:11:22:33:44:55"
    ip: 10.20.0.500
`, nil).mustFailWith(t, "dhcp-reservations[0].ip", "10.20.0.500")
}

// A MAC is the reservation's natural key, so two entries carrying one are two
// answers to a question with one answer — the same ambiguity as two networks
// sharing a name.
func TestValidateCatchesDuplicateReservedMACs(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "00:11:22:33:44:55"
    ip: 10.20.0.50
  - mac: "00:11:22:33:44:55"
    ip: 10.20.0.51
`, nil).mustFailWith(t, "dhcp-reservations[1].mac", "00:11:22:33:44:55", "already")
}

// The one natural key in the file that is not case-sensitive. The Controller
// lower-cases every MAC it stores and refuses a second record for one whatever
// case it arrives in, so these two entries are one reservation written twice
// and unifig has to say so rather than apply them in file order.
func TestValidateCatchesTwoReservationsForOneMACInDifferentCases(t *testing.T) {
	runValidate(t, `dhcp-reservations:
  - mac: "AA:BB:CC:DD:EE:FF"
    ip: 10.20.0.50
  - mac: "aa:bb:cc:dd:ee:ff"
    ip: 10.20.0.51
`, nil).mustFailWith(t, "dhcp-reservations[1].mac", "case")
}

// The address is checked against the Controller rather than against this file,
// on the same reasoning as a firewall policy's zone (ADR-0010): the networks
// this file defines are not the only ones the site has, so a reservation on a
// network unifig does not manage is perfectly valid config.
func TestValidateAcceptsAReservationOnANetworkTheFileSaysNothingAbout(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnet: 10.20.0.1/24

dhcp-reservations:
  - mac: "00:11:22:33:44:55"
    ip: 10.99.0.50
`, nil).mustPass(t)
}

// A WAN slot is a Setting, and its key is the Controller's own name for a
// physical uplink rather than a name the operator chose — so the file names the
// slot it means, and unifig only ever updates it.
func TestValidateAcceptsAWANSlotWithPPPoECredentialsFromTheEnvironment(t *testing.T) {
	runValidate(t, `wan:
  - slot: WAN
    type: pppoe
    username: isp-user
    password: ${WAN_PASSWORD}
`, map[string]string{"WAN_PASSWORD": "correct-horse-battery"}).mustPass(t)
}

// The same rule as everywhere else (ADR-0004): a field the file leaves out is
// one unifig does not manage, so `- slot: WAN` is a complete entry.
func TestValidateAcceptsAWANSlotThatManagesNothingYet(t *testing.T) {
	runValidate(t, `wan:
  - slot: WAN
`, nil).mustPass(t)
}

// Which slots a router has is the router's answer, not the schema's — so what
// validate can catch offline is something that is not a slot name at all. A
// slot the Controller does not have is reported when unifig reads it.
func TestValidateRejectsSomethingThatIsNotASlotName(t *testing.T) {
	runValidate(t, `wan:
  - slot: Fibre
`, nil).mustFailWith(t, "line 2", "wan[0].slot", `"Fibre"`, "WAN2")
}

func TestValidateRejectsAConnectionTypeUnifigDoesNotModel(t *testing.T) {
	runValidate(t, `wan:
  - slot: WAN
    type: carrier-pigeon
`, nil).mustFailWith(t, "line 3", "wan[0].type", `"carrier-pigeon"`, `"pppoe"`)
}

func TestValidateCatchesTwoEntriesForOneWANSlot(t *testing.T) {
	res := runValidate(t, `wan:
  - slot: WAN
    type: dhcp
  - slot: WAN
    type: pppoe
`, nil).mustFailWith(t, "line 4", "wan[1].slot", "WAN")

	if strings.Count(res.stderr, "already configured") != 1 {
		t.Errorf("a duplicated slot should be reported once, got:\n%s", res.stderr)
	}
}

// A PPPoE password is a secret on exactly the same terms as a WLAN passphrase:
// the complaint says what was wrong with it, never what it was.
func TestValidateNeverEchoesAPPPoEPassword(t *testing.T) {
	const secret = "no spaces allowed"
	res := runValidate(t, `wan:
  - slot: WAN
    type: pppoe
    username: isp-user
    password: ${WAN_PASSWORD}
`, map[string]string{"WAN_PASSWORD": secret})

	if res.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1 — the Controller refuses a password with spaces in it\nstderr: %s",
			res.exitCode, res.stderr)
	}
	if strings.Contains(res.stderr, secret) {
		t.Errorf("validate printed the password it was complaining about:\n%s", res.stderr)
	}
	if !strings.Contains(res.stderr, "wan[0].password") {
		t.Errorf("stderr should say which field was wrong, got:\n%s", res.stderr)
	}
}

// Encrypted DNS is the second Setting and the first singleton: a Controller has
// exactly one, so the section is a mapping with no key to match on.
func TestValidateAcceptsEncryptedDNSWithAStampFromTheEnvironment(t *testing.T) {
	runValidate(t, `encrypted-dns:
  state: custom
  servers:
    - name: Quad9
      stamp: ${DNS_STAMP}
`, map[string]string{"DNS_STAMP": "sdns://AgMAAAAAAAAAAAAPZG5zLmV4YW1wbGUuY29t"}).mustPass(t)
}

// The same rule as everywhere else (ADR-0004): a field the file leaves out is
// one unifig does not manage. `state:` alone leaves the servers alone, and the
// section with nothing in it manages nothing.
func TestValidateAcceptsAnEncryptedDNSSectionThatManagesNothingYet(t *testing.T) {
	runValidate(t, "encrypted-dns:\n  state: auto\n", nil).mustPass(t)
	runValidate(t, "encrypted-dns: {}\n", nil).mustPass(t)
}

// `servers: []` is the file saying there should be none, which is a different
// statement from leaving the key out — and both have to be sayable.
func TestValidateAcceptsAnEmptyListOfCustomDNSServers(t *testing.T) {
	runValidate(t, "encrypted-dns:\n  servers: []\n", nil).mustPass(t)
}

func TestValidateRejectsAnEncryptedDNSStateUnifigDoesNotModel(t *testing.T) {
	runValidate(t, "encrypted-dns:\n  state: encrypted\n", nil).
		mustFailWith(t, "line 2", "encrypted-dns.state", `"encrypted"`, `"custom"`)
}

func TestValidateRejectsACustomDNSServerWithNoStamp(t *testing.T) {
	runValidate(t, `encrypted-dns:
  servers:
    - name: Quad9
`, nil).mustFailWith(t, "encrypted-dns.servers[0]", "stamp")
}

func TestValidateCatchesTwoCustomDNSServersSharingAName(t *testing.T) {
	res := runValidate(t, `encrypted-dns:
  servers:
    - name: Quad9
      stamp: sdns://AgMAAAAAAAAAAAAPZG5zLmV4YW1wbGUuY29t
    - name: Quad9
      stamp: sdns://AgMAAAAAAAAAAAAQZG5zMi5leGFtcGxlLmNvbQ
`, nil).mustFailWith(t, "line 5", "encrypted-dns.servers[1].name", "Quad9")

	if strings.Count(res.stderr, "already defined") != 1 {
		t.Errorf("a duplicated name should be reported once, got:\n%s", res.stderr)
	}
}

// A DNS stamp is a secret on exactly the same terms as a WLAN passphrase and a
// PPPoE password: the complaint says what was wrong with it, never what it was.
// A stamp for a private endpoint carries the account it belongs to.
func TestValidateNeverEchoesADNSStamp(t *testing.T) {
	const secret = "sdns://not a stamp, and this half identifies somebody"
	res := runValidate(t, `encrypted-dns:
  state: custom
  servers:
    - name: Quad9
      stamp: ${DNS_STAMP}
`, map[string]string{"DNS_STAMP": secret})

	if res.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1 — that is not the shape of a DNS stamp\nstderr: %s",
			res.exitCode, res.stderr)
	}
	if strings.Contains(res.stderr, "identifies somebody") {
		t.Errorf("validate printed the stamp it was complaining about:\n%s", res.stderr)
	}
	if !strings.Contains(res.stderr, "encrypted-dns.servers[0].stamp") {
		t.Errorf("stderr should say which field was wrong, got:\n%s", res.stderr)
	}
	if !strings.Contains(res.stderr, "sdns://") {
		t.Errorf("stderr should say what a stamp looks like, got:\n%s", res.stderr)
	}
}

func TestValidateInterpolatesEnvVarsIntoValues(t *testing.T) {
	runValidate(t, `networks:
  - name: ${IOT_NAME}
    subnet: ${IOT_SUBNET}
`, map[string]string{
		"IOT_NAME":   "IoT",
		"IOT_SUBNET": "10.20.0.1/24",
	}).mustPass(t)
}

func TestValidateChecksTheInterpolatedValueNotThePlaceholder(t *testing.T) {
	// Proof that interpolation happened before validation: the complaint is
	// about what the environment supplied, not about the ${...} text.
	runValidate(t, `networks:
  - name: IoT
    subnet: ${IOT_SUBNET}
`, map[string]string{
		"IOT_SUBNET": "10.20.0.999",
	}).mustFailWith(t, "networks[0].subnet", "10.20.0.999")
}

func TestValidateFailsNamingAMissingEnvVar(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnet: ${IOT_SUBNET}
`, nil).mustFailWith(t, "line 3", "networks[0].subnet", "IOT_SUBNET")
}

func TestValidateNamesEveryMissingEnvVar(t *testing.T) {
	res := runValidate(t, `networks:
  - name: ${IOT_NAME}
    subnet: ${IOT_SUBNET}
`, nil).mustFailWith(t, "IOT_NAME", "IOT_SUBNET")

	if res.exitCode != 1 {
		t.Fatalf("exit code = %d, want 1", res.exitCode)
	}
}

func TestValidateDoesNotInterpolateKeys(t *testing.T) {
	// ${...} in a key position is not a reference, so this fails as an unknown
	// field rather than as a missing variable.
	res := runValidate(t, `networks:
  - name: IoT
    ${SUBNET_KEY}: 10.20.0.1/24
`, nil).mustFailWith(t, "unknown field")

	if strings.Contains(res.stderr, "not set in the environment") {
		t.Errorf("a ${...} key should not be treated as a variable reference, got:\n%s", res.stderr)
	}
}

func TestValidateDoesNotRescanInterpolatedValues(t *testing.T) {
	// A secret that happens to contain ${...} is inserted verbatim; it cannot
	// smuggle in a second reference.
	runValidate(t, `networks:
  - name: ${IOT_NAME}
`, map[string]string{
		"IOT_NAME": "${NOT_A_REFERENCE}",
	}).mustPass(t)
}

func TestValidateExplainsThatInterpolationProducesText(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: ${IOT_VLAN}
`, map[string]string{
		"IOT_VLAN": "20",
	}).mustFailWith(t, "networks[0].vlan", "integer", "${ENV_VAR}")
}

func TestValidateDoesNotBlameInterpolationForAHandWrittenValue(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    vlan: "20"
`, nil).mustFailWith(t, "networks[0].vlan", "integer")

	if strings.Contains(res.stderr, "${ENV_VAR}") {
		t.Errorf("no variable was interpolated here, so interpolation should not be mentioned, got:\n%s", res.stderr)
	}
}

func TestUnknownVerbPrintsUsage(t *testing.T) {
	res := run(t, "vaidate")

	if res.exitCode != 1 {
		t.Errorf("exit code = %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "validate") {
		t.Errorf("usage should list the validate command, got: %s", res.stderr)
	}
}

func TestValidateWithTooManyArgumentsPrintsUsage(t *testing.T) {
	res := run(t, "validate", "one.yaml", "two.yaml")

	if res.exitCode != 1 {
		t.Errorf("exit code = %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "usage:") {
		t.Errorf("stderr should be the usage text, got: %s", res.stderr)
	}
}
