// Package cli_test drives unifig's whole command layer the way the operator
// does — a verb, arguments, an environment, and whatever lands on stdout,
// stderr and the exit code.
//
// The e2e suite is the house pattern for this, and it runs the real binary
// against a real dockerized Controller. Validate cannot live there: it is
// offline by design, and requiring Docker to prove that would be an odd way to
// demonstrate that no Controller is needed. So these tests take the highest
// seam that is still Docker-free — cli.Run, the top-level engine behind main —
// and assert only on what a shell would see. Being an external test package,
// they cannot reach past that seam even by accident.
package cli_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/liambeeton/unifig/internal/cli"
)

// unreachableController is a Controller that is guaranteed not to answer:
// port 1 on the loopback interface. Validate runs with this in the
// environment throughout, so any test passing here is a test that proves
// validate never opened a connection.
const unreachableController = "https://127.0.0.1:1"

type result struct {
	exitCode int
	stdout   string
	stderr   string
}

// runValidate writes body to a config file and validates it, with connection
// config that would fail loudly if validate ever tried to use it.
func runValidate(t *testing.T, body string, env map[string]string) result {
	t.Helper()
	path := filepath.Join(t.TempDir(), "unifig.yaml")
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	for name, value := range env {
		t.Setenv(name, value)
	}
	return run(t, "validate", path)
}

func run(t *testing.T, args ...string) result {
	t.Helper()
	t.Setenv("UNIFIG_HOST", unreachableController)
	t.Setenv("UNIFIG_API_KEY", "unused-by-validate")

	var stdout, stderr strings.Builder
	code := cli.Run(context.Background(), args, noInput, &stdout, &stderr)
	return result{exitCode: code, stdout: stdout.String(), stderr: stderr.String()}
}

// noInput is a closed stdin. Nothing these tests run should ever ask the
// operator a question, so anything that does gets EOF and has to cope.
var noInput = strings.NewReader("")

// mustPass fails the test unless validate accepted the file, printing what it
// objected to.
func (r result) mustPass(t *testing.T) result {
	t.Helper()
	if r.exitCode != 0 {
		t.Fatalf("validate exited %d, want 0\nstderr: %s", r.exitCode, r.stderr)
	}
	return r
}

// mustFailWith fails the test unless validate rejected the file with a message
// mentioning every fragment — the things an operator needs in order to act.
func (r result) mustFailWith(t *testing.T, fragments ...string) result {
	t.Helper()
	if r.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1\nstdout: %s\nstderr: %s", r.exitCode, r.stdout, r.stderr)
	}
	if r.stdout != "" {
		t.Errorf("validate should print nothing on stdout when it fails, got: %s", r.stdout)
	}
	for _, fragment := range fragments {
		if !strings.Contains(r.stderr, fragment) {
			t.Errorf("stderr should mention %q, got:\n%s", fragment, r.stderr)
		}
	}
	return r
}

// exportedYAML is the shape `unifig export` writes, as an independent literal
// rather than something generated by the code under test.
const exportedYAML = `networks:
  - name: Default
    subnet: 192.168.1.1/24
  - name: IoT
    vlan: 20
    subnet: 10.20.0.1/24
`

func TestValidateAcceptsWhatExportProduces(t *testing.T) {
	runValidate(t, exportedYAML, nil).mustPass(t)
}

func TestValidateReportsSuccessOnStdout(t *testing.T) {
	res := runValidate(t, exportedYAML, nil).mustPass(t)

	if !strings.Contains(res.stdout, "is valid") {
		t.Errorf("stdout should confirm the file is valid, got: %q", res.stdout)
	}
	if res.stderr != "" {
		t.Errorf("stderr should stay empty on success, got: %q", res.stderr)
	}
}

func TestValidateNeedsNoControllerAndNoConnectionConfig(t *testing.T) {
	// Not merely unreachable — absent. Export fails without these; validate
	// must not care that they are missing.
	t.Setenv("UNIFIG_HOST", "")
	t.Setenv("UNIFIG_API_KEY", "")
	if err := os.Unsetenv("UNIFIG_HOST"); err != nil {
		t.Fatal(err)
	}
	if err := os.Unsetenv("UNIFIG_API_KEY"); err != nil {
		t.Fatal(err)
	}

	path := filepath.Join(t.TempDir(), "unifig.yaml")
	if err := os.WriteFile(path, []byte(exportedYAML), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}

	var stdout, stderr strings.Builder
	if code := cli.Run(context.Background(), []string{"validate", path}, noInput, &stdout, &stderr); code != 0 {
		t.Fatalf("validate exited %d with no connection config, want 0\nstderr: %s", code, stderr.String())
	}
}

func TestValidateDefaultsToUnifigYAMLInTheWorkingDirectory(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "unifig.yaml"), []byte(exportedYAML), 0o600); err != nil {
		t.Fatalf("writing config: %v", err)
	}
	t.Chdir(dir)

	res := run(t, "validate").mustPass(t)
	if !strings.Contains(res.stdout, "unifig.yaml") {
		t.Errorf("stdout should name the file it validated, got: %q", res.stdout)
	}
}

func TestValidateReportsAMissingFile(t *testing.T) {
	res := run(t, "validate", filepath.Join(t.TempDir(), "nowhere.yaml"))

	if res.exitCode != 1 {
		t.Fatalf("validate exited %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "nowhere.yaml") {
		t.Errorf("stderr should name the file it could not read, got: %s", res.stderr)
	}
	// The likeliest reason there is no config file is that the operator has
	// not made one yet, and export is how they do that.
	if !strings.Contains(res.stderr, "unifig export") {
		t.Errorf("stderr should point at export as the way to create one, got: %s", res.stderr)
	}
}

func TestValidateRejectsAMultiDocumentFileRatherThanIgnoringTheRest(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
---
wlans:
  - name: Home IoT
    network: IoT
`, nil).mustFailWith(t, "one YAML document")
}

func TestValidateRejectsAMisspelledField(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnett: 10.20.0.1/24
`, nil).mustFailWith(t, "line 3", "networks[0].subnett", "subnett")
}

func TestValidateRejectsAnUnknownSection(t *testing.T) {
	runValidate(t, `netwroks:
  - name: IoT
`, nil).mustFailWith(t, "netwroks")
}

func TestValidateRejectsAMissingName(t *testing.T) {
	runValidate(t, `networks:
  - vlan: 20
`, nil).mustFailWith(t, "networks[0]", "name")
}

func TestValidateRejectsAMalformedSubnet(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnet: 10.20.0.1
`, nil).mustFailWith(t, "line 3", "networks[0].subnet", "10.20.0.1/24")
}

func TestValidateRejectsAnOutOfRangeVLAN(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 5000
`, nil).mustFailWith(t, "networks[0].vlan", "4094")
}

func TestValidateReportsEveryProblemAtOnce(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    subnet: nonsense
  - vlan: 5000
`, nil).mustFailWith(t, "networks[0].subnet", "networks[1]", "networks[1].vlan")

	// File order, so the list reads like the file the operator is looking at.
	subnet := strings.Index(res.stderr, "networks[0].subnet")
	vlan := strings.Index(res.stderr, "networks[1].vlan")
	if subnet > vlan {
		t.Errorf("problems should be listed in file order, got:\n%s", res.stderr)
	}
}

func TestValidateRejectsAnEmptyFile(t *testing.T) {
	runValidate(t, "# nothing here yet\n", nil).mustFailWith(t, "empty")
}

func TestValidateRejectsBrokenYAML(t *testing.T) {
	runValidate(t, "networks: [\n", nil).mustFailWith(t, "YAML")
}

func TestValidateCatchesAWLANPointingAtAnUndefinedNetwork(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: 20
wlans:
  - name: Home IoT
    network: Gest
`, nil).mustFailWith(t, "line 6", `wlans[0].network`, `"Gest"`, `"IoT"`)
}

func TestValidateAcceptsAWLANPointingAtADefinedNetwork(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
`, nil).mustPass(t)
}

// The whole point of `${ENV_VAR}`: a committed config file that carries a
// passphrase without carrying the passphrase.
func TestValidateAcceptsAPassphraseSuppliedByTheEnvironment(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    passphrase: ${GUEST_PASSPHRASE}
`, map[string]string{"GUEST_PASSPHRASE": "correct horse battery"}).mustPass(t)
}

// A passphrase the config leaves out is a passphrase unifig does not manage,
// the same rule as every other omitted field (ADR-0004).
func TestValidateAcceptsAWLANWithNoPassphrase(t *testing.T) {
	runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
`, nil).mustPass(t)
}

// The bounds are the Controller's own: it refuses a WPA-PSK passphrase outside
// 8 to 64 characters, so unifig refuses one offline rather than letting an
// apply get halfway and stop.
func TestValidateRejectsAPassphraseTheControllerWouldRefuse(t *testing.T) {
	for _, supplied := range []struct{ what, value, want string }{
		{"too short", "short", "8 characters"},
		{"too long", strings.Repeat("a", 65), "64 characters"},
		// Caught here rather than by the Controller partway through an apply.
		{"not printable ASCII", "pässwörd123", "printable ASCII"},
	} {
		t.Run(supplied.what, func(t *testing.T) {
			runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    passphrase: ${GUEST_PASSPHRASE}
`, map[string]string{"GUEST_PASSPHRASE": supplied.value}).
				mustFailWith(t, "line 7", "wlans[0].passphrase", supplied.want)
		})
	}
}

// A validation message is printed, logged and pasted into bug reports, so the
// one thing it must never contain is the secret it is complaining about.
func TestValidateNeverEchoesAPassphrase(t *testing.T) {
	const secret = "sh0rt"
	for _, supplied := range []struct{ what, body, value string }{
		{"too short", "passphrase: ${GUEST_PASSPHRASE}\n", secret},
		{"too long", "passphrase: ${GUEST_PASSPHRASE}\n", strings.Repeat(secret, 20)},
		// The one that pays for the secretFields list: a pattern failure quotes
		// what it rejected everywhere else in unifig.
		{"not printable ASCII", "passphrase: ${GUEST_PASSPHRASE}\n", "pässwörd" + secret},
		{"the wrong type", "passphrase:\n      - ${GUEST_PASSPHRASE}\n", secret},
	} {
		t.Run(supplied.what, func(t *testing.T) {
			res := runValidate(t, `networks:
  - name: Guest
    vlan: 30
wlans:
  - name: Home Guest
    network: Guest
    `+supplied.body, map[string]string{"GUEST_PASSPHRASE": supplied.value})

			if res.exitCode != 1 {
				t.Fatalf("validate exited %d, want 1\nstderr: %s", res.exitCode, res.stderr)
			}
			if strings.Contains(res.stderr, secret) {
				t.Errorf("validate printed the passphrase it was complaining about:\n%s", res.stderr)
			}
		})
	}
}

func TestValidateCatchesDuplicateNetworkNames(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    vlan: 20
  - name: IoT
    vlan: 21
`, nil).mustFailWith(t, "line 4", "networks[1].name", `"IoT"`)

	if strings.Count(res.stderr, "already defined") != 1 {
		t.Errorf("a duplicated name should be reported once, got:\n%s", res.stderr)
	}
}

func TestValidateInterpolatesEnvVarsIntoValues(t *testing.T) {
	runValidate(t, `networks:
  - name: ${IOT_NAME}
    subnet: ${IOT_SUBNET}
`, map[string]string{
		"IOT_NAME":   "IoT",
		"IOT_SUBNET": "10.20.0.1/24",
	}).mustPass(t)
}

func TestValidateChecksTheInterpolatedValueNotThePlaceholder(t *testing.T) {
	// Proof that interpolation happened before validation: the complaint is
	// about what the environment supplied, not about the ${...} text.
	runValidate(t, `networks:
  - name: IoT
    subnet: ${IOT_SUBNET}
`, map[string]string{
		"IOT_SUBNET": "10.20.0.999",
	}).mustFailWith(t, "networks[0].subnet", "10.20.0.999")
}

func TestValidateFailsNamingAMissingEnvVar(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    subnet: ${IOT_SUBNET}
`, nil).mustFailWith(t, "line 3", "networks[0].subnet", "IOT_SUBNET")
}

func TestValidateNamesEveryMissingEnvVar(t *testing.T) {
	res := runValidate(t, `networks:
  - name: ${IOT_NAME}
    subnet: ${IOT_SUBNET}
`, nil).mustFailWith(t, "IOT_NAME", "IOT_SUBNET")

	if res.exitCode != 1 {
		t.Fatalf("exit code = %d, want 1", res.exitCode)
	}
}

func TestValidateDoesNotInterpolateKeys(t *testing.T) {
	// ${...} in a key position is not a reference, so this fails as an unknown
	// field rather than as a missing variable.
	res := runValidate(t, `networks:
  - name: IoT
    ${SUBNET_KEY}: 10.20.0.1/24
`, nil).mustFailWith(t, "unknown field")

	if strings.Contains(res.stderr, "not set in the environment") {
		t.Errorf("a ${...} key should not be treated as a variable reference, got:\n%s", res.stderr)
	}
}

func TestValidateDoesNotRescanInterpolatedValues(t *testing.T) {
	// A secret that happens to contain ${...} is inserted verbatim; it cannot
	// smuggle in a second reference.
	runValidate(t, `networks:
  - name: ${IOT_NAME}
`, map[string]string{
		"IOT_NAME": "${NOT_A_REFERENCE}",
	}).mustPass(t)
}

func TestValidateExplainsThatInterpolationProducesText(t *testing.T) {
	runValidate(t, `networks:
  - name: IoT
    vlan: ${IOT_VLAN}
`, map[string]string{
		"IOT_VLAN": "20",
	}).mustFailWith(t, "networks[0].vlan", "integer", "${ENV_VAR}")
}

func TestValidateDoesNotBlameInterpolationForAHandWrittenValue(t *testing.T) {
	res := runValidate(t, `networks:
  - name: IoT
    vlan: "20"
`, nil).mustFailWith(t, "networks[0].vlan", "integer")

	if strings.Contains(res.stderr, "${ENV_VAR}") {
		t.Errorf("no variable was interpolated here, so interpolation should not be mentioned, got:\n%s", res.stderr)
	}
}

func TestUnknownVerbPrintsUsage(t *testing.T) {
	res := run(t, "vaidate")

	if res.exitCode != 1 {
		t.Errorf("exit code = %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "validate") {
		t.Errorf("usage should list the validate command, got: %s", res.stderr)
	}
}

func TestValidateWithTooManyArgumentsPrintsUsage(t *testing.T) {
	res := run(t, "validate", "one.yaml", "two.yaml")

	if res.exitCode != 1 {
		t.Errorf("exit code = %d, want 1", res.exitCode)
	}
	if !strings.Contains(res.stderr, "usage:") {
		t.Errorf("stderr should be the usage text, got: %s", res.stderr)
	}
}
