package main

import (
	"fmt"
	"slices"
	"strings"

	"github.com/liambeeton/unifig/internal/compat"
)

// render writes the published table.
//
// Every number and every tick in it came out of a test run; the prose around
// them is here because a table of ticks with no statement of what it does not
// cover is the kind of compatibility claim this whole exercise exists to avoid.
func render(m compat.Matrix) string {
	var b strings.Builder

	b.WriteString("# Compatibility\n\n")
	b.WriteString("<!--\nGenerated by `tools/compat` from what the test runs actually did. Do not edit by hand:\n" +
		"`make matrix` rewrites it, and CI fails a change that leaves it out of date.\n-->\n\n")

	fmt.Fprintf(&b,
		"unifig drives a Controller through an API Ubiquiti does not document (`docs/adr/0002-internal-api.md`),"+
			" so which UniFi Network versions it has been run against is a fact worth publishing rather than a"+
			" claim to make. Everything below came out of a run: a version is here because the whole"+
			" process-level suite passed against it, and a row is here because its tests are in the file it"+
			" names.\n\nThe floor is **%s**. Nothing older is tested — and nothing is refused, whatever it"+
			" says (see [what unifig does on a version that is not here](#what-unifig-does-on-a-version-that-is-not-here)).\n\n",
		m.Floor)

	renderContainer(&b, m)
	renderRecording(&b, m)
	renderWarning(&b, m)
	renderAdding(&b)

	return b.String()
}

func renderContainer(b *strings.Builder, m compat.Matrix) {
	b.WriteString("## Tested against a dockerized Controller\n\n")
	fmt.Fprintf(b, "CI boots `%s` at each of these versions and runs the whole suite against it — the"+
		" real unifig binary, over HTTPS, against a real Network application.\n\n", m.Image)

	header := []string{"Area"}
	header = append(header, m.Versions...)
	writeRow(b, header)
	writeRule(b, len(header))

	for _, area := range m.Areas {
		if area.Evidence != compat.FromContainer {
			continue
		}
		row := []string{area.Name}
		for _, version := range m.Versions {
			row = append(row, tick(slices.Contains(area.Versions, version)))
		}
		writeRow(b, row)
	}
	b.WriteString("\n")
}

func renderRecording(b *strings.Builder, m compat.Matrix) {
	replayed := recordingAreas(m)
	if len(replayed) == 0 {
		return
	}

	measured := slices.ContainsFunc(replayed, func(area compat.Coverage) bool { return len(area.Measurements) > 0 })

	b.WriteString("## Tested against a recording, not a container\n\n")
	fmt.Fprintf(b, "These areas are **not in the table above and cannot be**, so nothing here claims a"+
		" tested container version for them. They are tested at the same seam — the same binary, the same base"+
		" URL, the same API-key header — against responses recorded from a physical UniFi Dream Router"+
		" (`%s`, `docs/adr/0008-wan-slots-replay-recorded-responses.md`). That is one Controller version, and"+
		" it is named here rather than left to be inferred from their absence above.\n\n", m.Recording.Source)
	if measured {
		b.WriteString("A row naming a second version is one whose tests rest on something no recording could" +
			" hold. Which Controller answered *that* is under the table, because the column below cannot say" +
			" it and be read correctly.\n\n")
	}

	// Not "Recorded Controller version": a measurement was not recorded, and a
	// column heading that said so would be false about the one row that needs
	// the reader's attention most.
	writeRow(b, []string{"Area", "Controller version its evidence came off", "Why a container cannot answer for it"})
	writeRule(b, 3)
	for _, area := range replayed {
		version := "not passing"
		if len(area.Versions) > 0 {
			version = strings.Join(area.Versions, ", ")
		}
		if len(area.Versions) > 0 && len(area.Measurements) > 0 {
			// The row's own version cannot be left to speak for the tests that
			// rest on something measured elsewhere, so it says so where it is
			// read rather than only further down the page.
			version = fmt.Sprintf("%s, and %s where stated below", version, compat.ListOf(measuredVersions(area)))
		}
		writeRow(b, []string{area.Name, version, area.Why})
	}
	fmt.Fprintf(b, "\nRe-recording from a router on another firmware moves these rows with it: the"+
		" recorded version above is read out of the recording itself, not written down beside it."+
		" `make record-udr` is how that is done, and `%s/README.md` says what the files hold.\n\n",
		m.Recording.Source)
	if measured {
		b.WriteString("A version beside it in that column is the other kind entirely, and re-recording does not" +
			" move it: it *is* written down, in the test that rests on it, because it is about a request no" +
			" recording holds.\n\n")
	}

	if measured {
		renderMeasured(b, m, replayed)
	}
}

// renderMeasured is the exception to the row above it, and the reason the table
// can carry one: a recording is `GET`s, so what a replayed test asserts about a
// *write* was measured in a live session against whatever firmware the router
// was on that day (ADR-0036).
func renderMeasured(b *strings.Builder, m compat.Matrix, replayed []compat.Coverage) {
	b.WriteString("### What a replayed test was measured on, where the recording could not answer\n\n")
	fmt.Fprintf(b, "`make record-udr` is read-only — one `GET` per recorded file, and no writes at all — so"+
		" what the stand-in models about a **write** was never in `%s` to begin with. It was measured in a"+
		" live session against whatever firmware the router was running that day, and where that is not the"+
		" version above, saying so is the only way the row is a true statement about the tests it"+
		" covers.\n\n", m.Recording.Source)

	writeRow(b, []string{"Area", "Measured on", "What was measured"})
	writeRule(b, 3)
	for _, area := range replayed {
		for _, measurement := range area.Measurements {
			writeRow(b, []string{area.Name, measurement.Version, measurement.What})
		}
	}
	b.WriteString("\nNone of this says the behaviour is absent from the version the row above names — only" +
		" that nobody has asked it there, which is a different thing and the narrower of the two. A probe on" +
		" that firmware is what would move one of these lines up into the row; re-recording would not, because" +
		" a recording holds no writes to move.\n\n")
}

// measuredVersions is the Controllers a row's exceptions were measured on, in
// the order they are published below it.
func measuredVersions(area compat.Coverage) []string {
	var versions []string
	for _, measurement := range area.Measurements {
		if !slices.Contains(versions, measurement.Version) {
			versions = append(versions, measurement.Version)
		}
	}
	return versions
}

func renderWarning(b *strings.Builder, m compat.Matrix) {
	b.WriteString("## What unifig does on a version that is not here\n\n")
	b.WriteString("It says so, once, on stderr, and carries on:\n\n")
	b.WriteString("```\n")
	b.WriteString("unifig: " + m.Warning(m.NextMinor()) + "\n")
	b.WriteString("```\n\n")
	b.WriteString("Every online command does it — `plan`, `apply`, `export` — and none of them stops. An untested" +
		" Controller is one nobody has run the suite against, which is not the same as one anybody has found a" +
		" fault in, and unifig refusing to manage a router on that basis would be a worse answer than a" +
		" warning. The versions it checks against are the columns of the **first** table — the ones a whole" +
		" suite ran against — and deliberately not the recording's version below it: a recording is evidence" +
		" about the areas below, so going quiet for a Controller the areas above were never run against would" +
		" be the warning claiming more than anybody tested. They are compiled into the binary from" +
		" `internal/compat/matrix.json`, which is generated from these same runs.\n\n")
}

func renderAdding(b *strings.Builder) {
	b.WriteString("## Adding a version\n\n")
	b.WriteString("Put it in `compatibility.yaml` and run `make matrix`. That is the whole change: the CI matrix," +
		" the version a bare `make e2e` boots, this table and the warning are all read from that file and from" +
		" the runs it causes. There is no code to touch, and no second place to remember.\n")
}

func recordingAreas(m compat.Matrix) []compat.Coverage {
	var areas []compat.Coverage
	for _, area := range m.Areas {
		if area.Evidence == compat.FromRecording {
			areas = append(areas, area)
		}
	}
	return areas
}

func writeRow(b *strings.Builder, cells []string) {
	b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
}

func writeRule(b *strings.Builder, columns int) {
	b.WriteString("|" + strings.Repeat(" --- |", columns) + "\n")
}

func tick(passed bool) string {
	if passed {
		return "yes"
	}
	return "—"
}
